import { fetchShareData, shareId, trDate } from './_share-data.js';

const escape=value=>String(value).replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const scriptSafe=value=>JSON.stringify(value).replace(/</g,'\\u003c');

export default async function handler(request,response){
  const id=shareId(request.query.id);
  if(!id)return response.status(404).send('Paylaşım bulunamadı.');
  try{
    const data=await fetchShareData(id),origin='https://supertribun.com',canonical=`${origin}/t/${id}`,image=`${origin}/api/share-image?id=${id}`;
    const title=`${data.home_name} – ${data.away_name}: ${data.prediction_home}–${data.prediction_away}`;
    const description=`Kilitli SüperTribün tahmini. Sen de skorunu söyle, tribünde yerini al.`;
    response.setHeader('Content-Type','text/html; charset=utf-8');
    response.setHeader('Cache-Control','public, max-age=60, s-maxage=300, stale-while-revalidate=3600');
    response.status(200).send(`<!doctype html><html lang="tr"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${escape(title)} · SüperTribün</title><meta name="description" content="${escape(description)}"><link rel="canonical" href="${canonical}"><meta property="og:type" content="website"><meta property="og:site_name" content="SüperTribün"><meta property="og:title" content="${escape(title)}"><meta property="og:description" content="${escape(description)}"><meta property="og:url" content="${canonical}"><meta property="og:image" content="${image}"><meta property="og:image:width" content="1200"><meta property="og:image:height" content="1200"><meta property="og:image:alt" content="${escape(title)} kilitli tahmin kartı"><meta name="twitter:card" content="summary_large_image"><meta name="twitter:image" content="${image}"><link rel="icon" href="/favicon.png"><style>
*{box-sizing:border-box}body{margin:0;background:#f7f4ef;color:#181716;font-family:Inter,system-ui,-apple-system,sans-serif}.page{min-height:100vh;display:grid;place-items:center;padding:28px 18px 120px}.wrap{width:min(620px,100%)}.brand{width:230px;height:auto;margin:0 0 18px}.card{display:block;width:100%;border-radius:24px;border:1px solid #d8d1c8;box-shadow:0 20px 60px #35280f18}.copy{text-align:center;color:#655b50;line-height:1.6;margin:20px auto 16px}.actions{display:flex;gap:10px;justify-content:center;flex-wrap:wrap}.button{display:inline-flex;min-height:52px;align-items:center;justify-content:center;padding:13px 20px;border-radius:14px;background:#181716;color:#fff;text-decoration:none;font-weight:800}.button.secondary{background:#fff;color:#855800;border:1px solid #d8d1c8}.soon{text-align:center;color:#8a837b;font-size:13px}.foot{text-align:center;margin-top:24px;font-size:13px}.foot a{color:#655b50}.consent{position:fixed;left:14px;right:14px;bottom:14px;margin:auto;max-width:820px;background:#25221f;color:#fff;border-radius:18px;padding:18px;box-shadow:0 10px 40px #0005;display:none;gap:14px;align-items:center}.consent p{flex:1;margin:0;line-height:1.45}.consent button{border:1px solid #ffffff55;border-radius:11px;background:transparent;color:#fff;padding:10px 14px;font-weight:700;cursor:pointer}.consent .accept{background:#f2ae18;color:#181716;border-color:#f2ae18}@media(max-width:600px){.consent{align-items:stretch;flex-direction:column}.page{padding-top:20px}.brand{width:190px}}
</style></head><body><main class="page"><div class="wrap"><img class="brand" src="/logo.png" alt="SüperTribün"><img class="card" src="${image}" alt="${escape(title)} kilitli tahmin kartı"><p class="copy"><strong>${escape(data.home_name)} – ${escape(data.away_name)}</strong><br>${escape(trDate(data.kickoff_at))} · Kilitli tahmin ${data.prediction_home}–${data.prediction_away}</p><div class="actions"><a id="open-app" class="button" href="com.supertribun.app://t/${id}">Uygulamada aç</a><a class="button secondary" href="/">SüperTribün'ü keşfet</a></div><p class="soon">App Store ve Google Play bağlantıları yakında.</p><p class="foot"><a href="/gizlilik">Gizlilik</a> · <a href="/cerez-politikasi">Çerez tercihleri</a></p></div></main><aside id="consent" class="consent" aria-label="Ölçüm tercihi"><p>İzin verirsen bu paylaşımın açılmasını ve uygulama düğmesine tıklanmasını Vercel ile ölçeriz. İndirme sayısı değildir.</p><button id="reject">Reddet</button><button id="accept" class="accept">Kabul et</button></aside><script>
(()=>{const KEY='cookieConsent',VERSION='2026-09-20',LIFE=15552000000,bar=document.getElementById('consent');let enabled=false;
const read=()=>{try{const v=JSON.parse(localStorage.getItem(KEY));const now=Date.now();return v&&v.version===VERSION&&v.necessary===true&&typeof v.analytics==='boolean'&&typeof v.performance==='boolean'&&v.savedAt<=now&&v.expiresAt>now&&v.expiresAt===v.savedAt+LIFE?v:null}catch{return null}};
const inject=()=>{if(enabled)return;enabled=true;window.va=window.va||function(){(window.vaq=window.vaq||[]).push(arguments)};const s=document.createElement('script');s.defer=true;s.src='/_vercel/insights/script.js';s.dataset.disableAutoTrack='1';document.head.appendChild(s);window.va('pageview',{route:'/t/[id]',path:'/t/shared'})};
const save=analytics=>{const savedAt=Date.now();try{localStorage.setItem(KEY,JSON.stringify({version:VERSION,necessary:true,analytics,performance:false,savedAt,expiresAt:savedAt+LIFE}))}catch{}bar.style.display='none';if(analytics)inject()};
const consent=read();if(consent?.analytics)inject();else if(!consent)bar.style.display='flex';
document.getElementById('reject').addEventListener('click',()=>save(false));document.getElementById('accept').addEventListener('click',()=>save(true));document.getElementById('open-app').addEventListener('click',()=>{if(enabled)window.va('event',{name:'share_open_app_click',data:{location:'prediction_share'}})});
window.__SUPERTRIBUN_SHARE__=${scriptSafe({id,matchId:data.match_id})};})();
</script></body></html>`);
  }catch(error){
    const unavailable=String(error?.message||'').includes('SHARE_CONFIG');
    response.status(unavailable?503:404).send('Bu paylaşım şu anda görüntülenemiyor.');
  }
}
